version: "3.3"

services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbit_in_api
        environment:
            - RABBITMQ_DEFAULT_USER=root
            - RABBITMQ_DEFAULT_PASS=root
        ports:
            - "15672:15672"
            - "5672:5672"